AWSTemplateFormatVersion: "2010-09-09"
Description: Intentionally misconfigured for demo purposes. DO NOT DEPLOY.
Resources:
  PublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open RDP to the world
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "20"
      MasterUsername: admin
      MasterUserPassword: "{{resolve:secretsmanager:demo-db:SecretString:password}}"
      PubliclyAccessible: true
      StorageEncrypted: false
